---

# Copying configuration files to the robot

- name: Copying udev rules
  sudo: yes
  copy:
    src=pandora-gears.rules
    dest=/etc/udev/rules.d

- name: Copying grub config
  sudo: yes
  copy:
    src=grub
    dest=/etc/default/grub

- name: Copying blacklist config
  sudo: yes
  copy:
    src=blacklist.conf
    dest=/etc/modprobe.d/blacklist.conf

- name: Adding play_sound script
  sudo: yes
  copy:
    src=play_sound
    dest=/etc/network/if-up.d
    group=root
    owner=root
    mode="u=rwx"

- name: Copying the .bashrc
  sudo: no
  copy:
    src=bashrc
    dest=/home/pandora/.bashrc
    owner=pandora
    group=pandora

- name: Copying the .bash_aliases
  sudo: no
  copy:
    src=bash_aliases
    dest=/home/pandora/.bash_aliases
    owner=pandora
    group=pandora

- name: Copying the repostatus
  sudo: yes
  copy:
    src=repostatus.sh
    dest=/usr/local/bin
    owner=pandora
    group=pandora
    mode="u=rwx"

- name: Copying the device_check
  sudo: yes
  copy:
    src=device_check.sh
    dest=/usr/local/bin
    owner=pandora
    group=pandora
    mode="u=rwx"

- name: Copying the Findlibusb-1.0
  sudo: yes
  copy:
    src=Findlibusb-1.0.cmake
    dest=/usr/share/cmake-2.8/Modules
    owner=pandora
    group=pandora

# Giving access to groups

- name: Add pandora to dialout and video group
  sudo: yes
  user: name=pandora groups=dialout,video append=yes
