---

# Copying configuration files to the robot

- name: Copying udev rules
  sudo: yes
  copy:
    src=pandora-gears.rules
    dest=/etc/udev/rules.d

- name: Adding play_sound script
  sudo: yes
  copy:
    src=play_sound
    dest=/etc/network/if-up.d
    group=root
    owner=root
    mode="u=rwx"

- name: Copying the .bashrc
  sudo: yes
  copy:
    src=.bashrc
    dest=/home/pandora
    owner=pandora
    group=pandora

# Giving access to groups

- name: Add pandora to dialout and video group
  user: name=pandora groups=dialout,video append=yes
