---

# Deploying PANDORA's code

- name: Create pandora workspace
  file:
    path="{{ pandora_source }}"
    owner=pandora
    group=pandora
    recurse=yes
    state=directory

- name: Create catkin workspace
  file:
    path="{{ catkin_source  }}"
    owner=pandora
    group=pandora
    recurse=yes
    state=directory

#- name: Initialize pandora workspace
  #raw: source {{ ros_bash }} && cd {{ pandora_source }} && catkin_init_workspace

#- name: Initialize catkin workspace
  #raw: source {{ ros_bash }} && cd {{ catkin_source }} && catkin_init_workspace

- name: Create temp directory for the private key
  file: path={{ pandora_home_ssh }} state=directory
  tags: code

- name: Copy private key
  copy: src=github_key dest={{ pandora_home_ssh }}/private_key owner=pandora group=pandora mode=600
  tags: code

- name: Download PANDORA's source code
  tags: code
  git:
    repo={{ item.url }}
    dest={{ pandora_source }}/{{ item.name }}
    version={{ item.version }}
    accept_hostkey=yes
    key_file="{{ pandora_home_ssh }}/private_key"
  with_items: "{{ pandora_repos }}"

- name: Download navigation repo
  tags: code
  git:
    repo={{ item.url }}
    dest={{ catkin_source }}/{{ item.name }}
    version={{ item.version }}
    accept_hostkey=yes
  with_items: "{{ navigation_repo }}"

- name: Delete private key
  file: path="{{ pandora_home_ssh }}/private_key" state=absent

- name: ROSdep init
  sudo: yes
  raw: rosdep init

- name: ROSdep update
  sudo: yes
  raw: rosdep update

- name: ROSdep install
  raw: cd {{ pandora_workspace }} && sudo rosdep install --from-paths src --ignore-src --rosdistro hydro -y

- name: ROSdep install
  raw: cd {{ catkin_workspace }} && sudo rosdep install --from-paths src --ignore-src --rosdistro hydro -y

- name: Making pandora the owner
  sudo: yes
  file:
    path={{ pandora_workspace }}
    owner=pandora
    group=pandora
    recurse=yes
    state=directory
