---

# Deploying PANDORA's code

- name: Creating catkin workspace
  sudo: yes
  file:
    path="{{ pandora_source }}"
    owner=pandora
    group=pandora
    recurse=yes
    state=directory

#- name: Initialize catkin workspace
  #raw: source {{ ros_bash }} && cd {{ pandora_source }} && catkin_init_workspace

- name: Create temp directory for the private key
  file: path={{ pandora_home_ssh }} state=directory

- name: Copy private key
  copy: src=github_key dest={{ pandora_home_ssh }}/private_key owner=pandora group=pandora mode=600

- name: Downloading PANDORA's source code
  git:
    repo={{ item.url }}
    dest={{ pandora_source }}/{{ item.name }}
    version={{ item.version }}
    key_file="{{ pandora_home_ssh }}/private_key"
  with_items: "{{ pandora_repos }}"

- name: Delete private key
  file: path="{{ pandora_home_ssh }}/private_key" state=absent

- name: ROSdep update
  raw: rosdep update

- name: ROSdep install
  raw: cd {{ robot_workspace }} && rosdep install --from-paths src --ignore-src --rosdistro hydro -y

- name: Making pandora the owner
  sudo: yes
  file:
    path={{ robot_workspace }}
    owner=pandora
    group=pandora
    recurse=yes
    state=directory
