---
header_version: '3.2.0-70-generic'

vagrant_64:
    url: 'https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.1_x86_64.deb'
    filename: 'vagrant_1.7.1_x86_64.deb'
vagrant_32:
    url: 'https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.1_i686.deb'
    filename: 'vagrant_1.7.1_i688.deb'

master_ssh_key: "{{ lookup('pipe', 'cat *.pub') }}"
