#!/bin/sh

# Play a sound only when the wireless is connected.
[ "$IFACE" != "lo" ] || exit 0
[ "$IFACE" != "eth0" ] || exit 0
[ "$IFACE" != "eth0:1" ] || exit 0
[ "$IFACE" != "eth1" ] || exit 0

beep -f 500 -n -f 1000 -n -f 1500 -n -f 2000 -n -f 2500 -n -f 2000 -n -f 1500 -n -f 1000 -n -f 500
