#!/bin/sh
cores=$(grep -c ^processor /proc/cpuinfo 2>/dev/null)
[ "$cores" -eq "0" ] && cores=1
threshold="${cores:-1}.0"
if [ $(echo "`cut -f1 -d ' ' /proc/loadavg` < $threshold" | bc) -eq 1 ]; then
    echo
    echo "  \033[1;100mSystem Info\033[0m"
    echo -n "\033[1;35m"
    /usr/bin/landscape-sysinfo --exclude-sysinfo-plugins=LandscapeLink
    echo -n "\033[0m"
else
    echo
    echo "  \033[1;31mSystem information disabled due to load higher than $threshold\033[0m"
fi
