# General aliases
alias shutdown='sudo shutdown -h now'
alias reboot='sudo shutdown -r now'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# Pandora launchers
#alias robot-launch='roslaunch pandora_launchers robot.launch'
alias integration-launch='roslaunch pandora_launchers integration_test.launch'
alias stabilizer='roslaunch pandora_launchers stabilizer.launch'

# Hardware launchers
alias motors='roslaunch pandora_motor_hardware_interface motor_hardware_interface_and_controllers.launch'
alias linear='roslaunch pandora_linear_actuator_hardware_interface linear_actuator_hardware_interface_and_controllers.launch'
alias pixy='roslaunch pandora_pixy_hardware_interface pixy_hardware_interface_and_controllers.launch'
alias dynamixel='roslaunch pandora_dynamixel_hardware_interface dynamixel_hardware_interface_and_controllers.launch'
alias imu='roslaunch pandora_imu_hardware_interface imu_hardware_interface_and_controllers.launch device:=trax'
alias arm='roslaunch pandora_arm_hardware_interface arm_hardware_interface_and_controllers.launch'
alias hardware_tools='roslaunch pandora_hardware_tools hardware_tools.launch'

# Other launchers
alias agent='roscd pandora_fsm/src && ./agent_standalone.py ; cd -'
alias teleop='rosrun pandora_motor_control pandora_teleop_key'

# Monitor
alias cpu-temp='watch sensors'
alias batteries='rostopic echo /sensors/battery'

# Scripts
alias repo_status='repo_status.sh ~/pandora_ws/src hydro-devel master'
alias repo_reset='repo_reset.sh ~/pandora_ws/src origin hydro-devel'
alias device_check='device_check.sh ~/.device_list'

# Connections
alias raspberry='ssh pandora@10.0.1.1'
